import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
// import fetcher from "../lib/https-request";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [postData, setPostData] = useState<any>(null);
  const [getData, setGetData] = useState<any>(null);
  const [putData, setPutData] = useState<any>(null);
  const [deleteData, setDeleteData] = useState<any>(null);

  // async function handleTest(method: string) {
  //   let data;

  //   switch (method) {
  //     case "DELETE":
  //       data = await fetcher.delete("/api");
  //       setDeleteData(data);
  //       break;
  //     case "GET":
  //       data = await fetcher.get("/api");
  //       setGetData(data);
  //       break;
  //     case "POST":
  //       data = await fetcher.post("/api?userId=100", {
  //         foo: "bar",
  //         hello: "world",
  //       });
  //       setPostData(data);
  //       break;
  //     case "PUT":
  //       data = await fetcher.update("/api?id=23191", {
  //         foo: "fooooobar",
  //       });
  //       setPutData(data);
  //       break;
  //     default:
  //       break;
  //   }
  // }

  return (
    <div className={styles.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className={styles.base}>
        <pre>
          <code>{JSON.stringify(postData, null, 2)}</code>
        </pre>
        <button onClick={() => handleTest("POST")}>test POST</button>
      </div>
      <div className={styles.base}>
        <pre>
          <code>{JSON.stringify(getData, null, 2)}</code>
        </pre>
        <button onClick={() => handleTest("GET")}>test GET</button>
      </div>
      <div className={styles.base}>
        <pre>
          <code>{JSON.stringify(putData, null, 2)}</code>
        </pre>
        <button onClick={() => handleTest("PUT")}>test PUT</button>
      </div>
      <div className={styles.base}>
        <pre>
          <code>{JSON.stringify(deleteData, null, 2)}</code>
        </pre>
        <button onClick={() => handleTest("DELETE")}>test DELETE</button>
      </div> */}
    </div>
  );
};

export default Home;
